Feat/project listing
WildCodeSchool/DevHubConnect pull request #40
Opened 2023-02-27 13:12 UTC by Binou05

2023-02-27 15:02 UTC, FredericGalline requested changes

2023-02-27 15:02 UTC, FredericGalline commented on frontend/src/components/Project/ProjectListing/ProjectContainer/ProjectListingCard/ProjectListingCard.jsx
> +          <item direction="column" spacing={2}>
Remplacer directement par un Stack au lieu de Item

2023-02-27 15:02 UTC, FredericGalline commented on frontend/src/components/Project/ProjectListing/ProjectContainer/ProjectListingCard/ProjectListingCard.jsx
> +    <ButtonBase>
Remplacer par MUI Link plutot que ButtonBase

2023-02-27 15:02 UTC, FredericGalline commented on frontend/src/components/Project/ProjectListing/ProjectContainer/ProjectListingContainer.jsx
> +    <>
Inutille puisqu'il y a Stack juste apres

2023-02-27 15:02 UTC, FredericGalline commented on frontend/src/components/Project/ProjectSingle/ProjectSingleContainer/ProjectSingleDescription/ProjectSingleDescriptionContent/ProjectSingleDescriptionContent.jsx
> +          <item>
Voir si <item> est vraiment utile car le Stack du dessus semble suffisant

2023-02-27 15:02 UTC, FredericGalline commented on frontend/src/components/Project/ProjectSingle/ProjectSingleContainer/ProjectSingleDescription/ProjectSingleDescriptionContent/ProjectSingleDescriptionContent.jsx
> +        <Stack
Optimiser la structure avec des sous composants

2023-02-27 15:02 UTC, FredericGalline commented on frontend/src/components/Project/ProjectSingle/ProjectSingleContainer/ProjectSingleDescription/ProjectSingleDescriptionContent/ProjectSingleDescriptionContent.jsx
> +          <item>
Privilegier <Stack> plutot que <item>

2023-02-27 15:02 UTC, FredericGalline commented on frontend/src/components/Project/ProjectSingle/ProjectSingleContainer/ProjectSingleHeader/ProjectSingleHeader.jsx
> +        <br />
a supprimer

2023-02-28 12:41 UTC, FannyBonnet approved these changes

2023-02-28 13:00 UTC, HoiAn2010 approved these changes

2023-02-28 13:02 UTC, jejem8430 approved these changes

2023-02-28 13:03 UTC, merged